# backend/src/main/resources/application-prod.yml (para Render/UPM)
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  flyway:
    enabled: true
server:
  port: ${PORT:8080}
app:
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMinutes: 240
  cloudinary:
    cloud-name: "dlijkbqr9"
    api-key: "829682312575565"
    api-secret: "2fLZ6bLyJJGut1Fvn0uFNdAZ5KE"
